using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HexGrid : MonoBehaviour {
	
	public int width = 6;
	public int height = 6;

	public HexCell cellPrefab;
	
	HexCell[] cells;

	HexMesh hexMesh;

	void Awake () {
		
		//hexMesh = GetComponentInChildren<HexMesh>();
		
		cells = new HexCell[height * width];

		for (int z = 0, i = 0; z < height; z++) {
			for (int x = 0; x < width; x++) {
				CreateCell(x, z, i++);
			}
		}
	}
	
	void CreateCell (int x, int z, int i) {
		Vector3 position;
		position.x = (x + z * 0.5f - z / 2) * (HexMetrics.innerRadius * 2f);
		position.y = 0f;
		position.z = z * (HexMetrics.outerRadius * 1.5f);

		HexCell cell = cells[i] = Instantiate<HexCell>(cellPrefab);
		cell.transform.SetParent(transform, false);
		cell.transform.localPosition = position;
	}

	// Use this for initialization
	void Start () {
		//hexMesh.Triangulate(cells);
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}
